---
title: "Weight of Fish"
author: "Kaylie Brehm"
date: "Summer 2022"
output: 
  html_document:
    number_sections: true
    toc: true
---


```{r include=FALSE,echo=FALSE}
require(tigerstats)
require(tidyverse)

Fish = read.csv("Fish.csv")
Perch = filter(Fish, Species == "Perch")
Pike = filter(Fish, Species == "Pike")
Roach = filter(Fish, Species == "Roach")
```

# Predicting Fish Weight



## Perch

```{r}

pwt =  lm(Weight~ Length1 + Length2 + Length3 + Height, data = Perch)
summary(pwt)
```

```{r}
library(leaps)
regsubsets.out <-
    regsubsets(Weight ~ Length1+ Length2 + Length3 + Height,
               data = Perch,
               nbest = 2,       # 1 best model for each number of predictors
               nvmax = NULL,    # NULL for no limit on number of variables
               force.in = NULL, force.out = NULL,
               method = "exhaustive")
regsubsets.out
```

```{r}
summary.out <- summary(regsubsets.out)
as.data.frame(summary.out$outmat)
```

### Best Models

The best model would have all four variables. 

### Best Two regressor model

The best two regressor models is based on length 3 and height.

## Pike

```{r}

pwt =  lm(Weight~ Length1 + Length2 + Length3 + Height, data = Pike)
summary(pwt)
```

```{r}
library(leaps)
regsubsets.out <-
    regsubsets(Weight ~ Length1+ Length2 + Length3 + Height,
               data = Pike,
               nbest = 2,       # 1 best model for each number of predictors
               nvmax = NULL,    # NULL for no limit on number of variables
               force.in = NULL, force.out = NULL,
               method = "exhaustive")
regsubsets.out
```

```{r}
summary.out <- summary(regsubsets.out)
as.data.frame(summary.out$outmat)
```


### Best Models

### Best Two regressor model

## Roach

```{r}

pwt =  lm(Weight~ Length1 + Length2 + Length3 + Height, data = Roach)
summary(pwt)
```

```{r}
library(leaps)
regsubsets.out <-
    regsubsets(Weight ~ Length1+ Length2 + Length3 + Height,
               data = Roach,
               nbest = 2,       # 1 best model for each number of predictors
               nvmax = NULL,    # NULL for no limit on number of variables
               force.in = NULL, force.out = NULL,
               method = "exhaustive")
regsubsets.out
```

```{r}
summary.out <- summary(regsubsets.out)
as.data.frame(summary.out$outmat)
```

### Best Models

### Best Two regressor model

## Final Summary Statements